# Generated by Django 5.1 on 2025-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_version', models.CharField(help_text='Minimum required version (e.g., 1.0.0)', max_length=20)),
                ('update_url', models.URLField(help_text='Play Store or website URL where users can download the update', max_length=500)),
                ('force_update_enabled', models.BooleanField(default=False, help_text='Enable to force users to update')),
                ('update_message', models.TextField(default='A new version is available. Please update to continue using the app.', help_text='Message shown to users when they need to update')),
            ],
            options={
                'verbose_name': 'App Version Control',
            },
        ),
    ]
